include(":app", ":core")
include(":common")
include(":characters")
include(":location")
include(":home")
include(":episodes")
include(":search")
include(":videoplayer")
include(":registration")
include(":settings")
